version: '2'
services:
    jhipsterangularjs-app:
        image: jhipsterangularjs
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsterangularjs-mysql:3306/jhipsterangularjs?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8011:8011
    jhipsterangularjs-mysql:
        extends:
            file: mysql.yml
            service: jhipsterangularjs-mysql
